import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: NextRequest) {
  try {
    const { email, htmlContent, summary, timeRange } = await request.json();

    if (!email || !htmlContent || !summary) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Check for required environment variables
    if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.error('Missing SMTP environment variables');
      return NextResponse.json(
        { error: 'Email service not configured. Please contact administrator.' },
        { status: 503 }
      );
    }

    // Create transporter using environment variables
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    // Prepare email content
    const emailSubject = `Temperature Report - ${timeRange}`;
    const emailText = `Temperature Readings Report\n\n${summary}\n\nPlease see the attached HTML report for detailed information.`;

    // Send email
    const info = await transporter.sendMail({
      from: process.env.SMTP_FROM || process.env.SMTP_USER,
      to: email,
      subject: emailSubject,
      text: emailText,
      html: `
        <div style="font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #333;">🌡️ Temperature Readings Report</h1>
          <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="color: #0070f3; margin-top: 0;">Summary Statistics</h2>
            <pre style="white-space: pre-wrap; font-family: monospace; background: white; padding: 15px; border-radius: 4px;">${summary}</pre>
          </div>
          <p>The detailed HTML report is attached to this email.</p>
          <p style="color: #666; font-size: 14px; margin-top: 30px;">
            Generated by Temperature Monitor PWA
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `temperature-report-${Date.now()}.html`,
          content: htmlContent,
          contentType: 'text/html',
        },
      ],
    });

    return NextResponse.json({
      success: true,
      messageId: info.messageId,
    });
  } catch (error) {
    console.error('Email send error:', error);
    return NextResponse.json(
      { error: 'Failed to send email', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
